import { registerBundledSkill } from '../bundledSkills.js'

const HTML_OUTPUT_PROMPT = `# HTML Output: Generate Rich, Interactive Reports

When the user asks for complex analysis, reports, code reviews, plans, comparisons, or any content that would benefit from visual structure — output an HTML file instead of plain Markdown.

## When to Use HTML Output

HTML output is ideal for:
- **Reports & analysis**: data tables, comparisons, summaries with structured sections
- **Code review results**: multi-file reviews with diffs, issue severity badges, file-by-file breakdowns
- **Architecture & plans**: diagrams (ASCII art rendered in monospace), decision trees, dependency maps
- **Search results**: grouped findings with clickable links, metadata, categorization
- **Status & progress**: project status, task breakdowns, progress indicators
- **Any content over ~50 lines** where Markdown readability drops off

## How to Produce HTML Output

1. **Write the HTML file** using the FileWrite tool to a path like \`/tmp/claude-html-output.html\` (or any temp directory).
2. **Tell the user the file path** and suggest they open it in their browser.
3. Use a simple, clean HTML structure — the file should be self-contained (no external CSS or JS).

## HTML Template

Start every HTML output with this structure:

\`\`\`html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>DESCRIPTIVE TITLE</title>
  <style>
    :root {
      --bg: #ffffff; --fg: #1a1a2e; --muted: #6b7280;
      --border: #e5e7eb; --accent: #2563eb; --accent-bg: #eff6ff;
      --code-bg: #f3f4f6; --radius: 8px;
    }
    @media (prefers-color-scheme: dark) {
      :root { --bg: #0f172a; --fg: #e2e8f0; --muted: #94a3b8; --border: #334155; --accent: #60a5fa; --accent-bg: #1e3a5f; --code-bg: #1e293b; }
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: var(--fg); background: var(--bg); max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem; line-height: 1.7; font-size: 15px; }
    h1 { font-size: 1.8rem; margin: 2rem 0 1rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }
    h2 { font-size: 1.4rem; margin: 1.5rem 0 0.75rem; }
    h3 { font-size: 1.1rem; margin: 1rem 0 0.5rem; }
    p { margin: 0.75rem 0; }
    a { color: var(--accent); }
    table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.9rem; }
    th, td { padding: 0.6rem 0.8rem; text-align: left; border: 1px solid var(--border); }
    th { background: var(--accent-bg); font-weight: 600; }
    tr:nth-child(even) td { background: var(--code-bg); }
    code, pre { font-family: 'JetBrains Mono', 'Fira Code', Consolas, monospace; font-size: 0.85rem; }
    code { background: var(--code-bg); padding: 0.15em 0.4em; border-radius: 4px; }
    pre { background: var(--code-bg); padding: 1rem; border-radius: var(--radius); overflow-x: auto; margin: 1rem 0; }
    pre code { background: none; padding: 0; }
    blockquote { border-left: 4px solid var(--accent); padding: 0.5rem 1rem; margin: 1rem 0; color: var(--muted); background: var(--accent-bg); border-radius: 0 var(--radius) var(--radius) 0; }
    ul, ol { padding-left: 1.5rem; margin: 0.75rem 0; }
    .badge { display: inline-block; padding: 0.15em 0.6em; border-radius: 999px; font-size: 0.8rem; font-weight: 500; }
    .badge-ok { background: #d1fae5; color: #065f46; }
    .badge-warn { background: #fef3c7; color: #92400e; }
    .badge-err { background: #fee2e2; color: #991b1b; }
    footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.85rem; }
  </style>
</head>
<body>
  <!-- Your content here -->
  <footer><p>Generated by MiniClaude</p></footer>
</body>
</html>
\`\`\`

## Design Principles

1. **Self-contained**: No external CSS, JS, or font links. Everything inline.
2. **Dark mode**: Use CSS custom properties with \`prefers-color-scheme: dark\` fallback.
3. **Clean**: No gratuitous animations, no emoji overload, no "AI slop" design patterns.
4. **Scannable**: Use headings, tables, badges (<span class="badge badge-ok">OK</span>) for quick scanning.
5. **Portable**: The file should look great when opened directly in any browser — no server needed.

## Opening the File

After writing the HTML file, tell the user:
- The full path to the file
- They can open it by double-clicking or running \`start <path>\` (Windows) / \`open <path>\` (macOS)

## Anti-patterns to Avoid

- Don't use gradient backgrounds, non-brand emojis, or rounded containers with left accent bars
- Don't overuse Inter/Roboto — stick to system font stack
- Don't load external resources (Google Fonts, CDN CSS, analytics scripts)
- Don't make the HTML heavier than needed — aim for under 100KB
`

export function registerHtmlOutputSkill(): void {
  registerBundledSkill({
    name: 'html-output',
    description:
      '生成结构化的 HTML 报告，替代大段 Markdown 输出。适用于复杂分析、代码审查、架构方案等需要丰富视觉呈现的场景。',
    userInvocable: true,
    argumentHint: '[主题或内容描述]',
    async getPromptForCommand(args) {
      let prompt = HTML_OUTPUT_PROMPT
      if (args) {
        prompt += `\n\n## Current Task\n\nGenerate an HTML report for: ${args}`
      }
      return [{ type: 'text', text: prompt }]
    },
  })
}
