import { mkdirSync, existsSync } from 'fs'
import { join } from 'path'
import { tmpdir } from 'os'
import { writeFileSync } from './file.js'
import { openPath } from './browser.js'
import { logForDebugging } from './debug.js'
import { logError } from './log.js'

const HTML_OUTPUT_DIR = join(tmpdir(), 'claude-html')

/**
 * Sanitize a filename for cross-platform safety.
 * Removes path separators and restricts to safe characters.
 */
function sanitizeFilename(name: string): string {
  return name
    .replace(/[/\\:*?"<>|]/g, '_')
    .replace(/\s+/g, '_')
    .slice(0, 200)
}

/**
 * Default CSS for agent-generated HTML output.
 * Clean, readable, responsive — works without external dependencies.
 */
const DEFAULT_CSS = `
  :root {
    --bg: #ffffff;
    --fg: #1a1a2e;
    --muted: #6b7280;
    --border: #e5e7eb;
    --accent: #2563eb;
    --accent-bg: #eff6ff;
    --code-bg: #f3f4f6;
    --radius: 8px;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #0f172a;
      --fg: #e2e8f0;
      --muted: #94a3b8;
      --border: #334155;
      --accent: #60a5fa;
      --accent-bg: #1e3a5f;
      --code-bg: #1e293b;
    }
  }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    color: var(--fg);
    background: var(--bg);
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem 1.5rem;
    line-height: 1.7;
    font-size: 16px;
  }
  h1 { font-size: 2rem; margin: 2rem 0 1rem; border-bottom: 2px solid var(--border); padding-bottom: 0.5rem; }
  h2 { font-size: 1.5rem; margin: 1.75rem 0 0.75rem; }
  h3 { font-size: 1.2rem; margin: 1.25rem 0 0.5rem; }
  p { margin: 0.75rem 0; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  table { width: 100%; border-collapse: collapse; margin: 1rem 0; font-size: 0.95rem; }
  th, td { padding: 0.75rem 1rem; text-align: left; border: 1px solid var(--border); }
  th { background: var(--accent-bg); font-weight: 600; }
  tr:nth-child(even) td { background: var(--code-bg); }
  code, pre {
    font-family: 'JetBrains Mono', 'Fira Code', 'Cascadia Code', Consolas, monospace;
    font-size: 0.9rem;
  }
  code { background: var(--code-bg); padding: 0.15em 0.4em; border-radius: 4px; }
  pre { background: var(--code-bg); padding: 1rem; border-radius: var(--radius); overflow-x: auto; margin: 1rem 0; }
  pre code { background: none; padding: 0; }
  blockquote {
    border-left: 4px solid var(--accent);
    padding: 0.5rem 1rem;
    margin: 1rem 0;
    color: var(--muted);
    background: var(--accent-bg);
    border-radius: 0 var(--radius) var(--radius) 0;
  }
  ul, ol { padding-left: 1.5rem; margin: 0.75rem 0; }
  li { margin: 0.25rem 0; }
  img, svg { max-width: 100%; height: auto; border-radius: var(--radius); }
  hr { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
  .badge {
    display: inline-block;
    padding: 0.15em 0.6em;
    border-radius: 999px;
    font-size: 0.8rem;
    font-weight: 500;
    background: var(--accent-bg);
    color: var(--accent);
  }
  details { margin: 1rem 0; border: 1px solid var(--border); border-radius: var(--radius); padding: 0.5rem 1rem; }
  summary { cursor: pointer; font-weight: 600; padding: 0.5rem 0; }
  footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.85rem; }
`

/**
 * Wrap user-provided HTML content in a complete, self-contained document with
 * responsive base styles. If the content already contains <html> or <body> tags,
 * returns it as-is (assumes the caller provided a complete document).
 */
function wrapHtmlDocument(innerHtml: string, title: string): string {
  // If already a full document, return as-is
  if (/<html/i.test(innerHtml) || /<body/i.test(innerHtml)) {
    return innerHtml
  }

  // Escape accidental closing tags in content
  const safeContent = innerHtml
    .replace(/<\/html>/gi, '')
    .replace(/<\/body>/gi, '')

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>${DEFAULT_CSS}</style>
</head>
<body>
${safeContent}
  <footer>
    <p>Generated by MiniClaude · ${new Date().toLocaleString('zh-CN', { timeZone: 'Asia/Shanghai' })}</p>
  </footer>
</body>
</html>`
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

/**
 * Write self-contained HTML content to a temp file and optionally open it
 * in the system browser.
 *
 * @param content  - The HTML content (fragment or full document)
 * @param options  - { filename?: string; title?: string; open?: boolean }
 * @returns The absolute path to the written HTML file
 *
 * @example
 *   const path = await writeHtmlOutput('<h1>Hello</h1>', { title: 'Report' })
 *   // → 'C:\\Users\\...\\AppData\\Local\\Temp\\claude-html\\Report.html'
 *   // File is auto-opened in browser
 */
export async function writeHtmlOutput(
  content: string,
  options: {
    filename?: string
    title?: string
    open?: boolean
  } = {},
): Promise<string> {
  const filename = sanitizeFilename(
    options.filename || `mini-claude-output-${Date.now()}`,
  )
  const title = options.title || 'MiniClaude Output'
  const shouldOpen = options.open !== false // default: true (auto-open)

  // Ensure filename ends with .html
  const htmlFilename = filename.endsWith('.html') ? filename : `${filename}.html`

  // Create output directory
  if (!existsSync(HTML_OUTPUT_DIR)) {
    mkdirSync(HTML_OUTPUT_DIR, { recursive: true })
  }

  const filePath = join(HTML_OUTPUT_DIR, htmlFilename)
  const fullDocument = wrapHtmlDocument(content, title)

  try {
    writeFileSync(filePath, fullDocument)
    logForDebugging(`HTML output written to ${filePath} (${fullDocument.length} bytes)`)

    if (shouldOpen) {
      const opened = await openPath(filePath)
      if (!opened) {
        logForDebugging(`Failed to auto-open browser for ${filePath}`, { level: 'info' })
      }
    }
  } catch (error) {
    logError(error)
    throw new Error(
      `Failed to write HTML output: ${error instanceof Error ? error.message : String(error)}`,
    )
  }

  return filePath
}

/**
 * Quick one-liner: write HTML and return the path.
 * Opens in browser by default. Use when you don't need to configure options.
 */
export async function html(content: string, title?: string): Promise<string> {
  return writeHtmlOutput(content, { title })
}
